# Generated by Django 4.2.2 on 2023-06-27 21:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefone deve ser inserido no formato correto: '+554187941579'. Até 15 digitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de telefone')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('zip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip Code')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefone deve ser inserido no formato correto: '+554187941579'. Até 15 digitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', related_query_name='customer', to='users.company', verbose_name='Company')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
