# Generated by Django 4.2.2 on 2023-07-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_whatsapp_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('phone', 'company')},
        ),
    ]
