# Generated by Django 4.2.3 on 2023-11-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_historicalproduct_whatsapp_meta_id_and_more'),
        ('users', '0003_supplier_historicalsupplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('not_requested', 'Não solicitado'), ('requested', 'Solicitado'), ('delivered', 'Entregue')], default='not_requested', max_length=20, verbose_name='Status da Solicitação')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
