# Generated by Django 4.2.3 on 2023-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_historicalproduct_whatsapp_meta_id_and_more'),
        ('users', '0004_remove_supplier_products_supplierproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='suppliers', through='users.SupplierProduct', to='products.product', verbose_name='Produtos'),
        ),
    ]
