ALERTS = {"102": "Produto do whats app nao encontrado pelo ID Meta fornecido, criado através do fluxo do pedido"}
STATE_CHOICES = [
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins'),
]
INDUSTRY_CHOICES = [
        ('beauty', 'Beleza'),
        ('ecommerce', 'E-commerce'),
        ('education', 'Educação'),
        ('finance', 'Finanças'),
        ('food', 'Alimentação'),
        ('health', 'Saúde'),
        ('manufacturing', 'Manufatura'),
        ('other', 'Outro'),
        ('retail', 'Varejo'),
        ('services', 'Serviços'),
        ('tech', 'Tecnologia'),
]
EMPLOYEE_COUNT_CHOICES = [
    (1, '1-10'),
    (2, '11-50'),
    (3, '51-200'),
    (4, '201-500'),
    (5, '501-1000'),
    (6, '1001-5000'),
    (7, '5001-10,000'),
    (8, '10,001+'),
]