# Generated by Django 4.2.2 on 2023-07-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WppConnectSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('session_token', models.CharField(max_length=255, verbose_name='Token da Sessão')),
                ('session_name', models.CharField(max_length=255, verbose_name='Nome da Sessão')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to='users.company')),
            ],
            options={
                'verbose_name': 'Sessão do WppConnect',
                'verbose_name_plural': 'Sessões do WppConnect',
                'db_table': 'wppconnect_sessions',
            },
        ),
    ]
