# Generated by Django 4.2.2 on 2023-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_wppconnectsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='wppconnectsession',
            name='whats_api_provider',
            field=models.CharField(choices=[('wppconnect', 'WppConnect'), ('baileys', 'Baileys')], default='wppconnect', max_length=20),
        ),
    ]
