# Generated by Django 4.2.2 on 2023-07-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_wppconnectsession_whats_api_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wppconnectsession',
            old_name='whats_api_provider',
            new_name='whatsapp_api_service',
        ),
    ]
