# Generated by Django 4.2.2 on 2023-06-19 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('paid', models.BooleanField(choices=[(True, 'Pago'), (False, 'Não pago')], default=False)),
                ('payment_method', models.CharField(choices=[('D', 'Dinheiro'), ('C', 'Cartão'), ('B', 'Boleto'), ('P', 'Pix')], default='P', max_length=255)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2023, 6, 26, 21, 0, 17, 635539))),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.customer')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='users.seller')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='TicketOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('quantity', models.PositiveIntegerField()),
                ('used', models.BooleanField(default=False)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_order_item', to='sales.sale')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ticket')),
            ],
            options={
                'db_table': 'ticket_order_item',
            },
        ),
        migrations.CreateModel(
            name='ProductOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('quantity', models.PositiveIntegerField()),
                ('used', models.BooleanField(default=False)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_item', to='sales.sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'product_order_item',
            },
        ),
    ]
