# Generated by Django 4.2.3 on 2024-02-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor pago')),
                ('payment_method', models.CharField(choices=[('D', 'Dinheiro'), ('C', 'Cartão'), ('B', 'Boleto'), ('P', 'Pix')], default='P', max_length=255, verbose_name='Metodo de pagamento')),
                ('status', models.CharField(blank=True, choices=[('Cancelado', 'Cancelado'), ('Não enviado', 'Não enviado'), ('Separado', 'Separado'), ('Enviado', 'Enviado'), ('Recebido', 'Recebido')], default='Não enviado', max_length=100, null=True, verbose_name='Status')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Pago em: ')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderToSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('NR', 'Não solicitado'), ('RQ', 'Solicitado'), ('DL', 'Entregue')], default='NR', max_length=2, verbose_name='Status da Solicitação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('not_requested', 'Não solicitado'), ('requested', 'Solicitado'), ('delivered', 'Entregue')], default='not_requested', max_length=20, verbose_name='Status da Solicitação')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'product_order_items',
            },
        ),
    ]
