# Generated by Django 4.2.3 on 2024-02-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_items', to='sales.order', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='ordertosupplier',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ordertosupplier',
            name='orders',
            field=models.ManyToManyField(related_name='orders_to_supplier', to='sales.order', verbose_name='Pedidos'),
        ),
        migrations.AddField(
            model_name='ordertosupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='users.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.customer', verbose_name='Cliente'),
        ),
    ]
