# Generated by Django 4.2.3 on 2023-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Não enviado', 'Não enviado'), ('Recebido', 'Recebido')], default='Não enviado', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Não enviado', 'Não enviado'), ('Recebido', 'Recebido')], default='Não enviado', verbose_name='Status'),
        ),
    ]
