# Generated by Django 4.2.3 on 2023-11-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_historicalorder_status_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='amount_missing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Falta pagar'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_missing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Falta pagar'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor pago'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelado', 'Cancelado'), ('Não enviado', 'Não enviado'), ('Separado', 'Separado'), ('Enviado', 'Enviado'), ('Recebido', 'Recebido')], default='Não enviado', null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelado', 'Cancelado'), ('Não enviado', 'Não enviado'), ('Separado', 'Separado'), ('Enviado', 'Enviado'), ('Recebido', 'Recebido')], default='Não enviado', null=True, verbose_name='Status'),
        ),
    ]
