# Generated by Django 4.2.3 on 2023-11-07 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_supplier_historicalsupplier'),
        ('sales', '0005_remove_historicalorder_paid_remove_order_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductorderitem',
            name='status',
            field=models.CharField(choices=[('not_requested', 'Não solicitado'), ('requested', 'Solicitado'), ('delivered', 'Entregue')], default='not_requested', max_length=20, verbose_name='Status da Solicitação'),
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='status',
            field=models.CharField(choices=[('not_requested', 'Não solicitado'), ('requested', 'Solicitado'), ('delivered', 'Entregue')], default='not_requested', max_length=20, verbose_name='Status da Solicitação'),
        ),
        migrations.CreateModel(
            name='OrderToSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('NR', 'Não solicitado'), ('RQ', 'Solicitado'), ('DL', 'Entregue')], default='NR', max_length=2, verbose_name='Status da Solicitação')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa')),
                ('orders', models.ManyToManyField(related_name='orders_to_supplier', to='sales.order', verbose_name='Pedidos')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='users.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrderToSupplier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('request_status', models.CharField(choices=[('NR', 'Não solicitado'), ('RQ', 'Solicitado'), ('DL', 'Entregue')], default='NR', max_length=2, verbose_name='Status da Solicitação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.company', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'historical order to supplier',
                'verbose_name_plural': 'historical order to suppliers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
