# Generated by Django 4.2.3 on 2023-12-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_historicalproductorderitem_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='amount_missing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount_missing',
        ),
    ]
