# Generated by Django 4.2.3 on 2023-12-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_historicalorder_amount_missing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='productorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade'),
        ),
    ]
