# Generated by Django 4.2.3 on 2024-02-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('alias', models.CharField(max_length=255, verbose_name='Alias')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recommendation_text', models.TextField(help_text='Mensagem de recomendação enviada ao cliente, sugerindo um produto da categoria B, caso o carrinho não contenha produtos dessa categoria.', verbose_name='Texto de Recomendação')),
                ('recommendation_image', models.ImageField(blank=True, null=True, upload_to='category_recomendations_images/')),
            ],
            options={
                'verbose_name': 'Recomendação por categoria',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('retailer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código do item')),
                ('whatsapp_meta_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID produto Meta')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='Link no Whatsapp')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('url_secondary', models.URLField(blank=True, null=True, verbose_name='URL Secundaria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Imagem')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'db_table': 'images',
            },
        ),
    ]
