# Generated by Django 4.2.3 on 2024-02-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='category_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_category_a', to='products.category', verbose_name='Categoria A'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='category_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_category_b', to='products.category', verbose_name='Categoria B'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='categories', related_query_name='category', to='products.product', verbose_name='Produtos'),
        ),
    ]
