# Generated by Django 4.2.2 on 2023-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrecommendation',
            name='recommendation_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_recomendations_images/'),
        ),
    ]
