# Generated by Django 4.2.2 on 2023-07-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_featured_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryaffinity',
            name='text_recomendation',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de Recomendação'),
        ),
    ]
